export default [
    {
        id: "c001",
        name: "Toyota Corolla",
        make: "Toyota",
        model: "Corolla",
        year: 2022,
        size: "compact",
        category: "economy",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 33,
        pricePerDay: 35,
        currency: "USD",
        available: true,
        location: { city: "Los Angeles", lat: 34.0522, lng: -118.2437 },
        mileageLimitPerDay: 150, // miles
        deposit: 200,
        rating: 4.5,
        reviewsCount: 342,
        images: [
            "/assets/cars/toyota-corolla-1.jpg",
            "/assets/cars/toyota-corolla-2.jpg"
        ],
        features: ["air conditioning", "bluetooth", "backup camera", "cruise control"],
        extras: [
            { code: "gps", name: "GPS", pricePerDay: 8 },
            { code: "child_seat", name: "Child Seat", pricePerDay: 5 }
        ],
        insuranceIncluded: false,
        insurancePricePerDay: 10,
        licenseRequirement: "valid driver's license",
        tags: ["reliable", "fuel-efficient"]
    },
    {
        id: "c002",
        name: "Honda Civic",
        make: "Honda",
        model: "Civic",
        year: 2021,
        size: "compact",
        category: "economy",
        seats: 5,
        doors: 4,
        transmission: "manual",
        fuelType: "gasoline",
        mpg: 32,
        pricePerDay: 33,
        currency: "USD",
        available: true,
        location: { city: "San Francisco", lat: 37.7749, lng: -122.4194 },
        mileageLimitPerDay: 140,
        deposit: 200,
        rating: 4.6,
        reviewsCount: 210,
        images: [
            "/assets/cars/honda-civic-1.jpg"
        ],
        features: ["air conditioning", "android auto", "apple carplay"],
        extras: [{ code: "additional_driver", name: "Additional Driver", pricePerDay: 7 }],
        insuranceIncluded: true,
        insurancePricePerDay: 0,
        licenseRequirement: "valid driver's license",
        tags: ["manual", "city"]
    },
    {
        id: "c003",
        name: "Ford Focus",
        make: "Ford",
        model: "Focus",
        year: 2019,
        size: "compact",
        category: "standard",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 28,
        pricePerDay: 29,
        currency: "USD",
        available: true,
        location: { city: "Seattle", lat: 47.6062, lng: -122.3321 },
        mileageLimitPerDay: 120,
        deposit: 150,
        rating: 4.1,
        reviewsCount: 98,
        images: ["/assets/cars/ford-focus-1.jpg"],
        features: ["air conditioning", "bluetooth"],
        extras: [],
        insuranceIncluded: false,
        insurancePricePerDay: 9,
        licenseRequirement: "valid driver's license",
        tags: ["budget"]
    },
    {
        id: "c004",
        name: "Nissan Altima",
        make: "Nissan",
        model: "Altima",
        year: 2020,
        size: "mid-size",
        category: "intermediate",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 30,
        pricePerDay: 42,
        currency: "USD",
        available: true,
        location: { city: "Chicago", lat: 41.8781, lng: -87.6298 },
        mileageLimitPerDay: 160,
        deposit: 250,
        rating: 4.3,
        reviewsCount: 157,
        images: ["/assets/cars/nissan-altima-1.jpg"],
        features: ["air conditioning", "heated seats", "cruise control", "backup camera"],
        extras: [{ code: "ski_rack", name: "Ski Rack", pricePerDay: 6 }],
        insuranceIncluded: false,
        insurancePricePerDay: 12,
        licenseRequirement: "valid driver's license",
        tags: ["comfortable", "family"]
    },
    {
        id: "c005",
        name: "Chevrolet Malibu",
        make: "Chevrolet",
        model: "Malibu",
        year: 2021,
        size: "mid-size",
        category: "intermediate",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 29,
        pricePerDay: 40,
        currency: "USD",
        available: true,
        location: { city: "Houston", lat: 29.7604, lng: -95.3698 },
        mileageLimitPerDay: 150,
        deposit: 220,
        rating: 4.2,
        reviewsCount: 110,
        images: ["/assets/cars/chevy-malibu-1.jpg"],
        features: ["air conditioning", "bluetooth", "apple carplay"],
        extras: [{ code: "wi-fi", name: "Onboard Wi-Fi", pricePerDay: 7 }],
        insuranceIncluded: true,
        insurancePricePerDay: 0,
        licenseRequirement: "valid driver's license",
        tags: ["comfortable"]
    },
    {
        id: "c006",
        name: "Volkswagen Jetta",
        make: "Volkswagen",
        model: "Jetta",
        year: 2020,
        size: "compact",
        category: "economy",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 31,
        pricePerDay: 34,
        currency: "USD",
        available: false,
        location: { city: "Phoenix", lat: 33.4484, lng: -112.0740 },
        mileageLimitPerDay: 140,
        deposit: 180,
        rating: 4.0,
        reviewsCount: 68,
        images: ["/assets/cars/vw-jetta-1.jpg"],
        features: ["air conditioning", "cruise control"],
        extras: [],
        insuranceIncluded: false,
        insurancePricePerDay: 8,
        licenseRequirement: "valid driver's license",
        tags: ["value"]
    },
    {
        id: "c007",
        name: "BMW 3 Series",
        make: "BMW",
        model: "3 Series",
        year: 2022,
        size: "full-size",
        category: "luxury",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 26,
        pricePerDay: 120,
        currency: "USD",
        available: true,
        location: { city: "New York", lat: 40.7128, lng: -74.0060 },
        mileageLimitPerDay: 200,
        deposit: 1000,
        rating: 4.8,
        reviewsCount: 540,
        images: [
            "/assets/cars/bmw-3-1.jpg",
            "/assets/cars/bmw-3-2.jpg"
        ],
        features: ["leather seats", "gps", "bluetooth", "heated seats"],
        extras: [{ code: "premium_insurance", name: "Premium Insurance", pricePerDay: 30 }],
        insuranceIncluded: false,
        insurancePricePerDay: 25,
        licenseRequirement: "full valid driver's license + 1 year driving experience",
        tags: ["premium", "business"]
    },
    {
        id: "c008",
        name: "Audi A4",
        make: "Audi",
        model: "A4",
        year: 2021,
        size: "full-size",
        category: "luxury",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 25,
        pricePerDay: 130,
        currency: "USD",
        available: true,
        location: { city: "Boston", lat: 42.3601, lng: -71.0589 },
        mileageLimitPerDay: 200,
        deposit: 1100,
        rating: 4.7,
        reviewsCount: 402,
        images: ["/assets/cars/audi-a4-1.jpg"],
        features: ["leather", "gps", "sunroof", "apple carplay"],
        extras: [{ code: "child_seat", name: "Child Seat", pricePerDay: 6 }],
        insuranceIncluded: false,
        insurancePricePerDay: 28,
        licenseRequirement: "full valid driver's license",
        tags: ["luxury", "executive"]
    },
    {
        id: "c009",
        name: "Jeep Wrangler",
        make: "Jeep",
        model: "Wrangler",
        year: 2020,
        size: "suv",
        category: "offroad",
        seats: 5,
        doors: 2,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 20,
        pricePerDay: 85,
        currency: "USD",
        available: true,
        location: { city: "Denver", lat: 39.7392, lng: -104.9903 },
        mileageLimitPerDay: 180,
        deposit: 500,
        rating: 4.6,
        reviewsCount: 289,
        images: ["/assets/cars/jeep-wrangler-1.jpg"],
        features: ["4x4", "bluetooth", "convertible top"],
        extras: [{ code: "offroad_kit", name: "Offroad Kit", pricePerDay: 15 }],
        insuranceIncluded: false,
        insurancePricePerDay: 20,
        licenseRequirement: "valid driver's license",
        tags: ["4x4", "adventure"]
    },
    {
        id: "c010",
        name: "Toyota RAV4",
        make: "Toyota",
        model: "RAV4",
        year: 2022,
        size: "suv",
        category: "crossover",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "hybrid",
        mpg: 35,
        pricePerDay: 65,
        currency: "USD",
        available: true,
        location: { city: "Portland", lat: 45.5051, lng: -122.6750 },
        mileageLimitPerDay: 170,
        deposit: 300,
        rating: 4.5,
        reviewsCount: 321,
        images: ["/assets/cars/toyota-rav4-1.jpg"],
        features: ["hybrid", "backup camera", "bluetooth", "roof rails"],
        extras: [{ code: "ski_rack", name: "Ski Rack", pricePerDay: 6 }],
        insuranceIncluded: true,
        insurancePricePerDay: 0,
        licenseRequirement: "valid driver's license",
        tags: ["hybrid", "family"]
    },
    {
        id: "c011",
        name: "Subaru Outback",
        make: "Subaru",
        model: "Outback",
        year: 2021,
        size: "suv",
        category: "crossover",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 27,
        pricePerDay: 70,
        currency: "USD",
        available: false,
        location: { city: "Salt Lake City", lat: 40.7608, lng: -111.8910 },
        mileageLimitPerDay: 160,
        deposit: 320,
        rating: 4.4,
        reviewsCount: 210,
        images: ["/assets/cars/subaru-outback-1.jpg"],
        features: ["all wheel drive", "roof rails", "bluetooth"],
        extras: [],
        insuranceIncluded: false,
        insurancePricePerDay: 15,
        licenseRequirement: "valid driver's license",
        tags: ["awd", "outdoors"]
    },
    {
        id: "c012",
        name: "Ford Transit",
        make: "Ford",
        model: "Transit",
        year: 2019,
        size: "van",
        category: "cargo",
        seats: 2,
        doors: 3,
        transmission: "automatic",
        fuelType: "diesel",
        mpg: 18,
        pricePerDay: 95,
        currency: "USD",
        available: true,
        location: { city: "Miami", lat: 25.7617, lng: -80.1918 },
        mileageLimitPerDay: 200,
        deposit: 600,
        rating: 4.0,
        reviewsCount: 74,
        images: ["/assets/cars/ford-transit-1.jpg"],
        features: ["cargo space", "tow hitch"],
        extras: [{ code: "ladder", name: "Ladder Rack", pricePerDay: 12 }],
        insuranceIncluded: false,
        insurancePricePerDay: 22,
        licenseRequirement: "commercial license may be required",
        tags: ["cargo", "moving"]
    },
    {
        id: "c013",
        name: "Mercedes-Benz C-Class",
        make: "Mercedes-Benz",
        model: "C-Class",
        year: 2022,
        size: "full-size",
        category: "luxury",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 24,
        pricePerDay: 150,
        currency: "USD",
        available: true,
        location: { city: "Atlanta", lat: 33.7490, lng: -84.3880 },
        mileageLimitPerDay: 220,
        deposit: 1500,
        rating: 4.9,
        reviewsCount: 610,
        images: ["/assets/cars/mercedes-c-1.jpg"],
        features: ["leather", "gps", "heated seats", "parking sensors"],
        extras: [{ code: "concierge_pickup", name: "Concierge Pickup", pricePerDay: 40 }],
        insuranceIncluded: false,
        insurancePricePerDay: 35,
        licenseRequirement: "full valid driver's license",
        tags: ["luxury", "executive"]
    },
    {
        id: "c014",
        name: "Tesla Model 3",
        make: "Tesla",
        model: "Model 3",
        year: 2023,
        size: "compact",
        category: "electric",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "electric",
        rangeMiles: 272,
        pricePerDay: 110,
        currency: "USD",
        available: true,
        location: { city: "San Jose", lat: 37.3382, lng: -121.8863 },
        mileageLimitPerDay: 250,
        deposit: 800,
        rating: 4.8,
        reviewsCount: 780,
        images: ["/assets/cars/tesla-model3-1.jpg"],
        features: ["autopilot", "fast charging", "bluetooth"],
        extras: [{ code: "supercharger_package", name: "Charging Credit", pricePerDay: 15 }],
        insuranceIncluded: false,
        insurancePricePerDay: 20,
        licenseRequirement: "valid driver's license + EV safety briefing",
        tags: ["electric", "autopilot"]
    },
    {
        id: "c015",
        name: "Nissan Leaf",
        make: "Nissan",
        model: "Leaf",
        year: 2020,
        size: "compact",
        category: "electric",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "electric",
        rangeMiles: 150,
        pricePerDay: 60,
        currency: "USD",
        available: true,
        location: { city: "Orlando", lat: 28.5383, lng: -81.3792 },
        mileageLimitPerDay: 120,
        deposit: 300,
        rating: 4.2,
        reviewsCount: 90,
        images: ["/assets/cars/nissan-leaf-1.jpg"],
        features: ["electric", "bluetooth"],
        extras: [],
        insuranceIncluded: false,
        insurancePricePerDay: 12,
        licenseRequirement: "valid driver's license + EV safety briefing recommended",
        tags: ["electric", "city"]
    },
    {
        id: "c016",
        name: "Mini Cooper Convertible",
        make: "Mini",
        model: "Cooper Convertible",
        year: 2019,
        size: "subcompact",
        category: "convertible",
        seats: 4,
        doors: 2,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 27,
        pricePerDay: 75,
        currency: "USD",
        available: true,
        location: { city: "San Diego", lat: 32.7157, lng: -117.1611 },
        mileageLimitPerDay: 130,
        deposit: 350,
        rating: 4.4,
        reviewsCount: 132,
        images: ["/assets/cars/mini-convertible-1.jpg"],
        features: ["convertible", "bluetooth", "cruise control"],
        extras: [{ code: "premium_audio", name: "Premium Audio", pricePerDay: 5 }],
        insuranceIncluded: false,
        insurancePricePerDay: 15,
        licenseRequirement: "valid driver's license",
        tags: ["fun", "weekend"]
    },
    {
        id: "c017",
        name: "Ford Mustang",
        make: "Ford",
        model: "Mustang",
        year: 2021,
        size: "sports",
        category: "convertible",
        seats: 4,
        doors: 2,
        transmission: "manual",
        fuelType: "gasoline",
        mpg: 20,
        pricePerDay: 130,
        currency: "USD",
        available: true,
        location: { city: "Las Vegas", lat: 36.1699, lng: -115.1398 },
        mileageLimitPerDay: 180,
        deposit: 800,
        rating: 4.6,
        reviewsCount: 270,
        images: ["/assets/cars/ford-mustang-1.jpg"],
        features: ["manual", "bluetooth", "sport package"],
        extras: [{ code: "track_insurance", name: "Track Insurance", pricePerDay: 50 }],
        insuranceIncluded: false,
        insurancePricePerDay: 30,
        licenseRequirement: "valid driver's license + 25+ age recommended",
        tags: ["sports", "manual"]
    },
    {
        id: "c018",
        name: "Hyundai Elantra",
        make: "Hyundai",
        model: "Elantra",
        year: 2022,
        size: "compact",
        category: "economy",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 33,
        pricePerDay: 31,
        currency: "USD",
        available: true,
        location: { city: "Columbus", lat: 39.9612, lng: -82.9988 },
        mileageLimitPerDay: 140,
        deposit: 180,
        rating: 4.0,
        reviewsCount: 86,
        images: ["/assets/cars/hyundai-elantra-1.jpg"],
        features: ["air conditioning", "bluetooth", "backup camera"],
        extras: [{ code: "additional_driver", name: "Additional Driver", pricePerDay: 6 }],
        insuranceIncluded: false,
        insurancePricePerDay: 9,
        licenseRequirement: "valid driver's license",
        tags: ["value"]
    },
    {
        id: "c019",
        name: "Kia Carnival",
        make: "Kia",
        model: "Carnival",
        year: 2023,
        size: "minivan",
        category: "family",
        seats: 7,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 22,
        pricePerDay: 95,
        currency: "USD",
        available: true,
        location: { city: "Philadelphia", lat: 39.9526, lng: -75.1652 },
        mileageLimitPerDay: 180,
        deposit: 450,
        rating: 4.5,
        reviewsCount: 144,
        images: ["/assets/cars/kia-carnival-1.jpg"],
        features: ["7 seats", "rear entertainment", "bluetooth"],
        extras: [{ code: "child_seat", name: "Child Seat", pricePerDay: 5 }],
        insuranceIncluded: false,
        insurancePricePerDay: 18,
        licenseRequirement: "valid driver's license",
        tags: ["family", "spacious"]
    },
    {
        id: "c020",
        name: "GMC Yukon",
        make: "GMC",
        model: "Yukon",
        year: 2021,
        size: "full-size suv",
        category: "premium suv",
        seats: 7,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 17,
        pricePerDay: 140,
        currency: "USD",
        available: true,
        location: { city: "Dallas", lat: 32.7767, lng: -96.7970 },
        mileageLimitPerDay: 220,
        deposit: 900,
        rating: 4.4,
        reviewsCount: 198,
        images: ["/assets/cars/gmc-yukon-1.jpg"],
        features: ["leather", "3rd row seats", "tow hitch"],
        extras: [{ code: "child_seat", name: "Child Seat", pricePerDay: 6 }],
        insuranceIncluded: false,
        insurancePricePerDay: 30,
        licenseRequirement: "valid driver's license",
        tags: ["large", "towing"]
    },
    {
        id: "c021",
        name: "Volkswagen ID.4",
        make: "Volkswagen",
        model: "ID.4",
        year: 2022,
        size: "suv",
        category: "electric",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "electric",
        rangeMiles: 250,
        pricePerDay: 95,
        currency: "USD",
        available: true,
        location: { city: "Austin", lat: 30.2672, lng: -97.7431 },
        mileageLimitPerDay: 200,
        deposit: 500,
        rating: 4.3,
        reviewsCount: 130,
        images: ["/assets/cars/vw-id4-1.jpg"],
        features: ["electric", "fast charging", "bluetooth"],
        extras: [{ code: "charging_cable", name: "Charging Cable", pricePerDay: 4 }],
        insuranceIncluded: false,
        insurancePricePerDay: 18,
        licenseRequirement: "valid driver's license + EV briefing recommended",
        tags: ["electric", "suv"]
    },
    {
        id: "c022",
        name: "Chevrolet Suburban",
        make: "Chevrolet",
        model: "Suburban",
        year: 2020,
        size: "full-size suv",
        category: "family",
        seats: 8,
        doors: 4,
        transmission: "automatic",
        fuelType: "gasoline",
        mpg: 16,
        pricePerDay: 145,
        currency: "USD",
        available: true,
        location: { city: "Kansas City", lat: 39.0997, lng: -94.5786 },
        mileageLimitPerDay: 220,
        deposit: 1000,
        rating: 4.2,
        reviewsCount: 95,
        images: ["/assets/cars/chevy-suburban-1.jpg"],
        features: ["8 seats", "dvd player", "towing package"],
        extras: [{ code: "roof_box", name: "Roof Box", pricePerDay: 12 }],
        insuranceIncluded: false,
        insurancePricePerDay: 32,
        licenseRequirement: "valid driver's license",
        tags: ["large", "group"]
    },
    {
        id: "c023",
        name: "Toyota Prius",
        make: "Toyota",
        model: "Prius",
        year: 2021,
        size: "compact",
        category: "hybrid",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "hybrid",
        mpg: 50,
        pricePerDay: 48,
        currency: "USD",
        available: true,
        location: { city: "Sacramento", lat: 38.5816, lng: -121.4944 },
        mileageLimitPerDay: 160,
        deposit: 240,
        rating: 4.5,
        reviewsCount: 230,
        images: ["/assets/cars/toyota-prius-1.jpg"],
        features: ["hybrid", "bluetooth", "backup camera"],
        extras: [{ code: "eco_package", name: "Eco Package", pricePerDay: 5 }],
        insuranceIncluded: false,
        insurancePricePerDay: 10,
        licenseRequirement: "valid driver's license",
        tags: ["hybrid", "economical"]
    },
    {
        id: "c024",
        name: "Rivian R1T",
        make: "Rivian",
        model: "R1T",
        year: 2023,
        size: "truck",
        category: "electric truck",
        seats: 5,
        doors: 4,
        transmission: "automatic",
        fuelType: "electric",
        rangeMiles: 314,
        pricePerDay: 220,
        currency: "USD",
        available: true,
        location: { city: "Boulder", lat: 40.01499, lng: -105.27055 },
        mileageLimitPerDay: 250,
        deposit: 1500,
        rating: 4.9,
        reviewsCount: 88,
        images: ["/assets/cars/rivian-r1t-1.jpg"],
        features: ["electric", "camp mode", "truck bed", "offroad package"],
        extras: [{ code: "camping_kit", name: "Camping Kit", pricePerDay: 25 }],
        insuranceIncluded: false,
        insurancePricePerDay: 40,
        licenseRequirement: "valid driver's license + 25+ age recommended",
        tags: ["electric", "adventure"]
    }
];